export const GET_USER = 'GET_USER';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';


export const ADD_GALLERY_IMAGE = 'ADD_GALLERY_IMAGE';
export const UPDATE_GALLERY_IMAGE = 'UPDATE_GALLERY_IMAGE';
export const DELETE_GALLERY_IMAGE = 'DELETE_GALLERY_IMAGE';

export const SET_PROGRESS_PERCENT = 'SET_PROGRESS_PERCENT';